FROM axoniq/axonserver:latest-dev

RUN curl -o /axonserver/exts/control-tower-extension-1.0-SNAPSHOT.jar https://download.axoniq.io/axonserver/control-tower-extension-1.0-SNAPSHOT.jar
RUN curl -o /axonserver/exts/spring-retry-1.3.4.jar https://repo.maven.apache.org/maven2/org/springframework/retry/spring-retry/1.3.4/spring-retry-1.3.4.jar

