:navtitle: Setting up AxonIQ Console
:reftext: Setting up your free AxonIQ Console account

= Introducing AxonIQ Console

link:https://console.axoniq.io[AxonIQ Console,role=external,window=_blank] is the tool we will use in this tutorial to show you how to monitor your distributed application built with Axon and identify any components that are not performing as expected or other bottlenecks and issues.

We will use the free plan of AxonIQ Console in this tutorial, which is sufficient to connect a small application and experience its features and benefits firsthand.

If you prefer to get a complete idea of what AxonIQ Console has to offer before creating your account, you can read about the different panels and dashboards in the xref:axoniq-console-getting-started:ac-monitor-axon-framework-applications:overview-tab.adoc["Monitoring Axon Framework Applications"] section of the xref:axoniq-console-getting-started:ROOT:index.adoc[AxonIQ Console Getting Started Guide.,window=_blank]

If you prefer to explore and discover its features by directly connecting an application, keep reading: We will help you to either connect your own version of the "Bike Rental" application or use a docker-based "Bike Rental" demo application we have already prepared for you.

== Set up your free AxonIQ Console account.

The first step is to set up your free AxonIQ Console account. To do this, simply follow the steps described in the following sections of the xref:axoniq-console-getting-started::index.adoc[AxonIQ Console Getting Started Guide]:

1. xref:axoniq-console-getting-started:ac-gs-setup:access.adoc[Register and create your free AxonIQ Console account]

2. xref:axoniq-console-getting-started:ac-gs-setup:setting-up-your-account.adoc#_part_1_setting_up_your_account[Configure your account details] and proceed to the next section in this guide when you are presented with a page that gives you the option to either connect your application or run the demo.

[NOTE]
====
AxonIQ Console provides detailed instructions con how to connect your own Java or Axon Framework based application, or alternatively, provides a `docker-compose.yaml` file that allows you to run a version of the `bike-rental` application that is already configured to connect to the AxonIQ Console environment you have just created.

In the second dialog of the xref:axoniq-console-getting-started:ac-gs-setup:setting-up-your-account.adoc[First time setup steps,window=_blank,role=external] step, you can choose your preferred option. You can try to follow the detailed steps provided directly by AxonIQ Console UI to connect your application and skip this guide directly to xref:monitoring/index.adoc[]
====







