:navtitle: Creating and Detecting Issues in your Application

= Detecting Issues in your Application

In this step of the tutorial, we will intentionally create some delays and errors in the `bike-rental' demo application that we have connected to our AxonIQ Console dashboard. After configuring the application to present some misbehavior or poor performance, we will see more clearly how AxonIQ Console helps us monitor and detect these issues in our application.

We will use the AxonFramework Firestarter library, which we added in the xref:monitoring/add-axon-firestarter.adoc[] step of this tutorial, and the set of features it provides to introduce the behavior problems in our application. This library is not intended to be used in production environments but for scenarios where we want to do some stress or chaos testing of our system.

NOTE: If you are using the Docker-based bike rental application downloaded during the AxonIQ Console sign-up process, the Axon FireStarter library is already included in all the modules of your application.

We will guide you through some scenarios in which we can show how to introduce specific problems and how AxonIQ Console helps you detect them.

- xref::monitoring/slow-event-handlers.adoc[]

:page-needs-improvement: content
:page-needs-content: Define independent error scenarios and have them as separate articles. i.e. Detecting a slow event handler, detecting a heavy aggregate (with no snapshots), detecting slow query handlers, ...


NOTE: We will add more scenarios to this list. If you are interested in how AxonIQ Console helps detect a specific type of problem, let us know your suggestions of content to be added here in the link:https://discuss.axoniq.io/c/axoniq-console/35[discuss forum category dedicated to AxonIQ Console]


