:navtitle: Components and Tools Used During this Guide.

= Components and Tools Used During This Guide.

These are the tools that we are going to use during this guide:

== AxonIQ Console

We will show you how to create your free account in AxonIQ Console in the first steps of this guide.

The main tool that we will use for this guide is AxonIQ Console, an online service that allows you to connect your application and provides a dashboard with a comprehensive view of your system behaviour, while it also allows you to step into more detailed information on each of the modules/components of your system.

AxonIQ Console also allows to configure alerts that will notify you in case of certain performance thresholds are trespassed.

== Axon Framework based application (optional).

This will be application that will be monitoring. During the guide, we will use the `bike-rental` demo application that you built with the xref:bikerental-demo::index.adoc[], but you can also use your own Axon Framework based application, if you already have one.

If you don't have an application built using Axon Framework ready, we will also provide you a working version of the `bike-rental` demo application that you can run easily with `docker`.


== Axon Firestarter library (optional).

In order to make things more interesting, we will try to cause performance problems in our running application. That way we could see the real power of AxonIQ Console detecting those problems.

To alter the application normal behaviour on purpose and create those performance issues in our application in an easy way, we will add to our application the https://github.com/AxonFramework/AxonFramework-FireStarter[Axon Framework Firestarter library,window=_blank,role=external].

NOTE: If you plan to use the `bike-rental-demo` application that we provide via docker images, don't worry, as this version already has this feature enabled.
