= Create New Axon Framework Multi-Project
:navtitle: Create New Project
:reftext: Creating A New AxonFramework Project

The first thing we need to do is to create a new project and configure the AxonFramework dependencies that will help us focusing on the business code.

== Create the root project
We will use Maven in this project. We want to create a project composed of several modules that can be deployed independently, so, we will create a multi-module project.

We will start by creating the root project: the project that will contain the different modules or subprojects. This corresponds to a root-pom maven project.

In order to create this root maven project you can use the IDE of your preference, making sure you specify the following values for the project properties:

[horizontal]
archetypeGroupId:: org.codehaus.mojo.archetypes
archetypeArtifactId:: pom-root
archetypeVersion:: RELEASE
groupId:: io.axoniq.demo.bikerental
artifactId:: bike-rental
version:: 0.0.1-SNAPSHOT

Alternatively, you can create the project from your console terminal with the following maven command:

[source,shell]
----
 mvn archetype:generate \
  -DarchetypeGroupId=org.codehaus.mojo.archetypes \
  -DarchetypeArtifactId=pom-root \
  -DarchetypeVersion=RELEASE \
  -DgroupId=io.axoniq.demo.bikerental \
  -DartifactId=bike-rental \
  -Dversion=0.0.1-SNAPSHOT \
  -DinteractiveMode=false
----

Maven will create a `bike-rental` folder with a maven project descriptor file: `pom.xml`. You can import the project in your favourite IDE.

We will be using Java 21 for this project, so we can explicitly configure it by adding this properties to the pom.xml file:

[source,xml]
----
include::example$root/pom.xml[tags=properties;!props-axonframework;!props-axoniq-console-client]
----

=== Configuring SpringBoot

Once we have our root project we need to configure it to use SpringBoot. There are two ways in which we could configure the springboot dependencies in our project: one is by adding them under the `<dependencyManagement>` section of the root `pom.xml` file.

Alternatively, we can make our root project depend on `org.springfamework.boot:spring-boot-starter-parent` which already defines all the dependencies required to use SpringBoot in our projects.

We will follow the second option. Open your `pom.xml` and add the following snippet right before the `<groupId>` tag:
[source,xml]
----
include::example$root/pom.xml[tag=spring-boot-starter-parent]
----

== Create the project modules.

We will start by having an unique main module where we will implement the bussiness logic of our bike rental application. The goal with AxonIQ technologies is to focus on a single application and avoiding the unnecesary complexity of dealing with multiple modules right from the start. And yet, we aim to build our module in such a way that it is prepared to evolve easily into different modules. That is what we call *evolutionary microservices*.

=== Creating the main rental module

Our main module will be the `rental` module. To create it you can use your IDE to add a new module or you can use the following maven command from the root bike-rental folder:

[source,shell]
----
 mvn archetype:generate -DgroupId=io.axoniq.demo.bikerental -DartifactId=rental -Dpackage=io.axoniq.demo.bikerental.rental -DinteractiveMode=false
----

After running the command you will see a new directory `rental` directory with a `rental/pom.xml` file which declares the project as a sub-module of the root project:

.rental/pom.xml
[source,xml]
----
include::example$rental/pom.xml[tag=parent]
----

At the same time the maven project descriptor of the root project has been modified to include the new module:

./pom.xml
[source,xml]
----
include::example$root/pom.xml[tags=modules;mod-rental;!*]
----

Your IDE should now show the new project as a submodule.

NOTE: If the IDE does not detect the new module, you may have to refresh the project structure and reload the Maven projects in your IDE.

=== Creating the core-api subproject

Although we are going to start with a main module for our bussiness logic, we also have already mentioned that we want to be prepared to split our project into different modules when we need to evolve into multiple modules (or microservices)

In order to be prepared to make that step later, we are going to have a module in which we will include the definition of the messages and clases that will be used to communicate the different modules. We will name this project as `core-api`

To create the `core-api` submodule, use your IDE to create a new Module (make sure you create it using the root project as the parent), or you can use the following maven command from the root project's folder:

[source,shell]
----
 mvn archetype:generate -DgroupId=io.axoniq.demo.bikerental -DartifactId=core-api -Dpackage=io.axoniq.demo.bikerental.coreapi -DinteractiveMode=false
----

After executing the command, you should see a new core-api project with a `pom.xml` file declaring the root project as the parent:

./core-api/pom.xml
[source,xml]
----
include::example$core-api/pom.xml[tag=parent]
----

And the maven descriptor in the root project now should also include the `core-api` as a module:

./pom.xml
[source,xml]
----
include::example$root/pom.xml[tags=modules;mod-rental;mod-core-api;!*]
----

Your IDE should recognize the two sub-projects as modules.

NOTE: If the IDE does not detect the new module, you may have to refresh the project structure and reload the Maven projects in your IDE.

=== Add dependencies for the main rental module

As the last step in creating the multi-module structure for our project, we will declare that the main `rental` module will use the `core-api` module.

In order to do that, declare the following dependency in the maven descriptor file for the `rental` module:

.rental/pom.xml
[source,xml]
----
include::example$rental/pom.xml[tags=dependencies;deps-core-api;!*]
----

With this last step, we are done with creating the structure for our project.

In the next step, we will learn how to bootstrap Axon Framework in our project.







